"use client";
import { ReactNode, useMemo, useState } from "react";
import { buildWorkloadProfile, getSelectedWorkload } from "./workload-mapper-utils";
import { sizingFields, workloadLibrary } from "./workload-mapper-data";
import { AiPattern, WorkloadFormState } from "./workload-mapper-types";

const aiPatterns: AiPattern[] = ["RAG", "Fine-tuning", "Training from scratch", "Inference only", "Analytics / ML pipeline", "HPC simulation", "Not sure yet"];
const initialState: WorkloadFormState = { workloadName: "", selectedWorkloadId: workloadLibrary[0]?.id ?? "", processImproved: "", successCriteria: "", aiPattern: "Not sure yet", dataTypes: [], dataSizeRange: "", dailyIngestRange: "", filePattern: "", freshnessRequirement: "", performanceTier: "near real-time", queryConcurrency: "", gpuDependency: "Medium", latencyRequirement: "", dataSensitivity: "High", auditTrail: "Strict", encryption: "Required", dataResidency: "Regional", retention: "", explainability: "Required", accessControls: "RBAC + ABAC", sizingInputs: { exactDataVolume: "", dailyIngestRate: "", fileObjectCount: "", queryConcurrency: "", modelSize: "", gpuRequirement: "", retentionPeriod: "", haDrRequirements: "", preferredVendors: "", budgetTimeline: "" } };

export function WorkloadMapper() {
  const [state, setState] = useState(initialState); const [walkthroughMode, setWalkthroughMode] = useState(false);
  const [customCategory, setCustomCategory] = useState("Custom"); const [customDescription, setCustomDescription] = useState(""); const [customAssumptions, setCustomAssumptions] = useState(""); const [customPressurePoints, setCustomPressurePoints] = useState("");
  const isCustom = state.selectedWorkloadId === "custom"; const selected = getSelectedWorkload(state.selectedWorkloadId);
  const profile = useMemo(() => buildWorkloadProfile(state, isCustom ? { name: state.workloadName, category: customCategory, description: customDescription, defaultPattern: state.aiPattern, assumptions: customAssumptions, pressurePoints: customPressurePoints } : undefined), [state, isCustom, customCategory, customDescription, customAssumptions, customPressurePoints]);

  return <div className="space-y-6 pb-10"><section className="rounded-2xl border border-border/60 bg-gradient-to-r from-slate-50 to-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-foreground/50">AI Workload Discovery Mapper</p><h1 className="mt-2 text-3xl font-semibold">Story-first discovery from use case to BOM readiness</h1><p className="mt-3 text-sm text-foreground/70">I am ramping from traditional infrastructure/storage into AI, HPC, and FSI workloads. This makes discovery repeatable from use case to BOM readiness gaps.</p></section>
  <div className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm font-medium">Walkthrough Mode (presentation view)</span><button className="rounded-md border px-3 py-1 text-sm" onClick={()=>setWalkthroughMode((v)=>!v)}>{walkthroughMode?"On":"Off"}</button></div>
  {walkthroughMode ? <Walkthrough profile={profile} workload={state.workloadName || selected?.name || "Custom workload"}/> : <section className="grid gap-6 xl:grid-cols-2"><div className="space-y-6"><Card title="Workload selection"><select className="w-full rounded-md border px-3 py-2 text-sm" value={state.selectedWorkloadId} onChange={(e)=>setState((p)=>({...p,selectedWorkloadId:e.target.value,aiPattern:"Not sure yet"}))}>{workloadLibrary.map((w)=><option key={w.id} value={w.id}>{w.category} — {w.name}</option>)}<option value="custom">Custom Workload</option></select>{isCustom ? <div className="mt-3 grid gap-3"><Input label="Workload name" value={state.workloadName} onChange={(v)=>setState((p)=>({...p,workloadName:v}))}/><Select label="Category" value={customCategory} options={["FSI","HPC / AI","Custom"]} onChange={setCustomCategory}/><Input label="Description / business goal" value={customDescription} onChange={setCustomDescription}/><Select label="Default AI pattern" value={state.aiPattern} options={aiPatterns} onChange={(v)=>setState((p)=>({...p,aiPattern:v as AiPattern}))}/><Input label="Assumptions (comma-separated)" value={customAssumptions} onChange={setCustomAssumptions}/><Input label="Likely pressure points (comma-separated)" value={customPressurePoints} onChange={setCustomPressurePoints}/></div> : selected && <p className="mt-3 text-sm text-foreground/70">{selected.description}</p>}</Card>
  <Card title="Questionnaire"><div className="grid gap-3 md:grid-cols-2"><Input label="Process improved" value={state.processImproved} onChange={(v)=>setState((p)=>({...p,processImproved:v}))}/><Input label="Success criteria" value={state.successCriteria} onChange={(v)=>setState((p)=>({...p,successCriteria:v}))}/><Select label="Performance tier" value={state.performanceTier} options={["real-time","near real-time","intraday","batch/end-of-day"]} onChange={(v)=>setState((p)=>({...p,performanceTier:v as WorkloadFormState['performanceTier']}))}/><Input label="Latency" value={state.latencyRequirement} onChange={(v)=>setState((p)=>({...p,latencyRequirement:v}))}/><Input label="Concurrency" value={state.queryConcurrency} onChange={(v)=>setState((p)=>({...p,queryConcurrency:v, sizingInputs:{...p.sizingInputs,queryConcurrency:v}}))}/><Select label="GPU dependency" value={state.gpuDependency} options={["Low","Medium","High"]} onChange={(v)=>setState((p)=>({...p,gpuDependency:v}))}/><Input label="Freshness" value={state.freshnessRequirement} onChange={(v)=>setState((p)=>({...p,freshnessRequirement:v}))}/><Select label="Data sensitivity" value={state.dataSensitivity} options={["Low","Moderate","High","Regulated / Highly sensitive"]} onChange={(v)=>setState((p)=>({...p,dataSensitivity:v}))}/><Select label="Audit trail requirement" value={state.auditTrail} options={["Baseline","Strict"]} onChange={(v)=>setState((p)=>({...p,auditTrail:v}))}/><Select label="Encryption" value={state.encryption} options={["Required","Optional"]} onChange={(v)=>setState((p)=>({...p,encryption:v}))}/><Select label="Data residency" value={state.dataResidency} options={["Local","Regional","Global"]} onChange={(v)=>setState((p)=>({...p,dataResidency:v}))}/><Input label="Retention" value={state.retention} onChange={(v)=>setState((p)=>({...p,retention:v}))}/><Select label="Explainability" value={state.explainability} options={["Required","Preferred","Not required"]} onChange={(v)=>setState((p)=>({...p,explainability:v}))}/><Input label="Access controls" value={state.accessControls} onChange={(v)=>setState((p)=>({...p,accessControls:v}))}/></div></Card>
  <Card title="BOM input capture"> <div className="grid gap-2 md:grid-cols-2">{sizingFields.map((f)=><Input key={f.key} label={f.label} value={state.sizingInputs[f.key]} onChange={(v)=>setState((p)=>({...p,sizingInputs:{...p.sizingInputs,[f.key]:v}}))}/>)}</div></Card></div>
  <div className="space-y-6"><Card title="Architecture pipeline"><div className="flex flex-wrap gap-2 text-xs">{profile.architectureSteps.map((s,i)=><span key={s} className="rounded-md border bg-muted/30 px-2 py-1">{i+1}. {s}</span>)}</div></Card><Card title="Top pressure points"><div className="flex flex-wrap gap-2">{profile.pressurePoints.map((p)=><span key={p} className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs">{p}</span>)}</div></Card><Card title="Reference building blocks">{Object.entries(profile.buildingBlocks).map(([k,v])=><div key={k} className="mb-3"><p className="text-sm font-semibold">{k}</p><ul className="list-disc pl-5 text-xs text-foreground/70">{v.map((i)=><li key={i}>{i}</li>)}</ul></div>)}</Card><Card title="BOM readiness (not a BOM)"><div className="h-3 rounded-full bg-muted"><div className="h-full rounded-full bg-emerald-500" style={{width:`${profile.readinessPercent}%`}}/></div><p className="mt-2 text-sm font-semibold">{profile.readinessPercent}% readiness</p><p className="mt-2 text-xs text-foreground/70">Known inputs: {profile.knownInputs.length} | Missing inputs: {profile.missingInputs.length}</p><ul className="mt-2 space-y-1 text-xs">{profile.missingInputs.slice(0,5).map((m)=><li key={m.label}><span className="font-medium">{m.label}</span>: {m.whyItMatters}</li>)}</ul></Card><Card title="Talk track"><ul className="space-y-2 text-sm">{profile.talkTrack.map((line)=><li key={line}>• {line}</li>)}</ul></Card></div></section>}
  </div>;
}

function Walkthrough({profile, workload}:{profile: ReturnType<typeof buildWorkloadProfile>; workload: string}) { return <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="text-2xl font-semibold">Walkthrough: {workload}</h2><p className="text-sm text-foreground/70">{profile.classification}</p><div className="flex flex-wrap gap-2">{profile.architectureSteps.map((s)=><span key={s} className="rounded-md border px-2 py-1 text-xs">{s}</span>)}</div><div className="flex flex-wrap gap-2">{profile.pressurePoints.map((p)=><span key={p} className="rounded-full bg-amber-50 px-3 py-1 text-xs">{p}</span>)}</div><p className="text-sm font-semibold">BOM readiness: {profile.readinessPercent}% (this is BOM readiness, not a BOM).</p><ul className="list-disc pl-5 text-sm">{profile.talkTrack.map((line)=><li key={line}>{line}</li>)}</ul></section>; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border border-border/60 bg-card p-4 shadow-sm"><h2 className="text-sm font-semibold uppercase tracking-wide text-foreground/60">{title}</h2><div className="mt-3">{children}</div></section>; }
function Input({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-medium text-foreground/70">{label}<input className="mt-1 w-full rounded-md border border-border/70 px-2 py-2 text-sm" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="text-xs font-medium text-foreground/70">{label}<select className="mt-1 w-full rounded-md border border-border/70 bg-background px-2 py-2 text-sm" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
