import { SizingField, WorkloadExamplePreset, WorkloadTemplate } from "./workload-mapper-types";

export const workloadLibrary: WorkloadTemplate[] = [
  { id: "fraud", name: "Fraud Detection & Investigation", category: "FSI", description: "Detect anomalies quickly, investigate patterns, and improve fraud response confidence.", defaultPattern: "RAG", defaultPressurePoints: ["data ingestion velocity", "retrieval freshness", "governance and auditability"], assumptions: ["Near real-time event feeds", "Mixed structured and unstructured investigation artifacts"] },
  { id: "risk", name: "Risk Modeling / Stress Testing", category: "FSI", description: "Run frequent portfolio stress analysis under evolving market conditions.", defaultPattern: "Analytics / ML pipeline", defaultPressurePoints: ["parallel data access", "scenario orchestration", "retention and lineage"], assumptions: ["Large historical data windows", "Compute spikes during quarterly stress cycles"] },
  { id: "trading", name: "Trading / Quant Research", category: "FSI", description: "Accelerate alpha research and intraday strategy iteration.", defaultPattern: "Analytics / ML pipeline", defaultPressurePoints: ["low latency data access", "high query concurrency", "checkpointing"], assumptions: ["Time-series heavy", "High-frequency model refresh"] },
  { id: "compliance", name: "Compliance / Document Intelligence", category: "FSI", description: "Extract obligations and evidence from policy and regulatory content.", defaultPattern: "RAG", defaultPressurePoints: ["embedding pipeline throughput", "explainability", "access controls"], assumptions: ["High-sensitivity documents", "Audit traceability is mandatory"] },
  { id: "fsi-rag", name: "RAG Knowledge Assistant", category: "FSI", description: "Enable secure knowledge retrieval for relationship managers and operations teams.", defaultPattern: "RAG", defaultPressurePoints: ["retrieval freshness", "vector search consistency", "data residency"], assumptions: ["Many small documents", "Strict role-based access"] },
  { id: "fsi-ft", name: "Model Training / Fine-tuning", category: "FSI", description: "Adapt domain models for financial language, risk, and client workflows.", defaultPattern: "Fine-tuning", defaultPressurePoints: ["GPU utilization", "checkpointing", "secure data staging"], assumptions: ["Controlled training datasets", "Periodic retraining cycles"] },
  { id: "ai-training", name: "Large-scale AI Training", category: "HPC / AI", description: "Train foundation or domain models with distributed training at scale.", defaultPattern: "Training from scratch", defaultPressurePoints: ["GPU utilization", "checkpointing", "parallel data access"], assumptions: ["Large batch windows", "Sustained high throughput storage"] },
  { id: "inference", name: "Inference Platform", category: "HPC / AI", description: "Serve interactive and API inference workloads with predictable latency.", defaultPattern: "Inference only", defaultPressurePoints: ["request concurrency", "model cache locality", "latency SLO adherence"], assumptions: ["Multi-tenant demand variability", "Autoscaling serving tiers"] },
  { id: "simulation", name: "Scientific Simulation", category: "HPC / AI", description: "Execute numerically intense simulation runs and iterative experiments.", defaultPattern: "HPC simulation", defaultPressurePoints: ["parallel file access", "interconnect bandwidth", "job scheduling efficiency"], assumptions: ["Large temporary datasets", "Burst-like compute scheduling"] },
  { id: "genomics", name: "Genomics / Life Sciences", category: "HPC / AI", description: "Process sequencing pipelines and AI-assisted analysis under compliance controls.", defaultPattern: "Analytics / ML pipeline", defaultPressurePoints: ["file/object explosion", "pipeline throughput", "data governance"], assumptions: ["Many small files", "Long retention for reproducibility"] },
  { id: "media", name: "Media / Rendering Pipeline", category: "HPC / AI", description: "Run rendering and media enhancement pipelines with tight delivery timelines.", defaultPattern: "Inference only", defaultPressurePoints: ["throughput orchestration", "storage bandwidth", "deadline-driven scaling"], assumptions: ["Mixed file sizes", "High sustained ingest during production windows"] },
];

export const sizingFields: SizingField[] = [
  { key: "exactDataVolume", label: "Exact data volume", whyItMatters: "Determines storage capacity, tiering strategy, and expected recovery windows." },
  { key: "dailyIngestRate", label: "Daily ingest rate", whyItMatters: "Shapes ingestion architecture and write throughput requirements." },
  { key: "fileObjectCount", label: "File/object count", whyItMatters: "Impacts metadata scaling, namespace performance, and indexing approach." },
  { key: "queryConcurrency", label: "Query concurrency", whyItMatters: "Guides compute sizing and caching strategy for peak user demand." },
  { key: "modelSize", label: "Model size", whyItMatters: "Influences memory footprint, model distribution, and serving pattern decisions." },
  { key: "gpuRequirement", label: "GPU requirement", whyItMatters: "Defines accelerator class, scheduling policy, and power/cooling footprint." },
  { key: "retentionPeriod", label: "Retention period", whyItMatters: "Establishes lifecycle policy, archival strategy, and compliance posture." },
  { key: "haDrRequirements", label: "HA/DR requirements", whyItMatters: "Sets availability targets and cross-site architecture expectations." },
  { key: "preferredVendors", label: "Preferred vendors", whyItMatters: "Highlights integration constraints and procurement dependencies early." },
  { key: "budgetTimeline", label: "Budget/timeline", whyItMatters: "Aligns solution shape with delivery phases and implementation risk." },
];

export const architecturePatterns: Record<string, string[]> = {
  RAG: ["Data Sources", "Ingestion / Normalization", "Chunking + Embedding", "High-Performance Data Platform", "Vector DB / Retrieval", "LLM / Model Serving", "Business App"],
  "Training from scratch": ["Data Lake / Corpus", "Distributed Preprocessing", "High-Throughput Training Storage", "GPU Training Cluster", "Checkpointing", "Evaluation", "Model Registry"],
  "Fine-tuning": ["Curated Dataset", "Data Quality + Labeling", "Fine-tuning Pipeline", "Accelerated Training", "Evaluation Harness", "Model Registry", "Deployment Targets"],
  "Inference only": ["Application/API Gateway", "Request Orchestration", "Prompt/Feature Processing", "Model Serving Tier", "Cache / Session State", "Observability / Guardrails"],
  "Analytics / ML pipeline": ["Data Sources", "Ingestion", "ETL/ELT + Feature Engineering", "Unified Data Platform", "ML/Analytics Execution", "Decision Apps"],
  "HPC simulation": ["Scientific Inputs", "Job Scheduler", "Parallel File/Data Platform", "HPC Compute Fabric", "Simulation Output Store", "Post-processing / Visualization"],
};

export const workloadExamplePresets: Record<string, WorkloadExamplePreset> = {
  fraud: {
    processImproved: "Triaging suspicious transactions and escalating investigation cases faster.",
    successCriteria: "Reduce false positives by 25% while cutting average investigation cycle time below 2 hours.",
    aiPattern: "RAG",
    dataTypes: ["structured", "unstructured", "streaming"],
    dataSizeRange: "45-70 TB transaction history + case-management evidence",
    dailyIngestRange: "0.8-1.6 TB/day with intraday event bursts",
    filePattern: "~6 billion transaction records + 12 million investigation notes/attachments",
    freshnessRequirement: "Near-real-time scoring with investigator context refreshed every 5-15 minutes",
    performanceTier: "near real-time",
    queryConcurrency: "250 fraud analysts and automated alert workflows at peak",
    gpuDependency: "Medium",
    latencyRequirement: "<300 ms for fraud-score API; <3 seconds for case-context retrieval",
    dataSensitivity: "Regulated / Highly sensitive",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Regional",
    retention: "7 years for transaction and investigation evidence",
    explainability: "Required",
    accessControls: "RBAC + ABAC with investigator segmentation",
    sizingInputs: { exactDataVolume: "52 TB active + 18 TB governed archive", dailyIngestRate: "0.8-1.6 TB/day", fileObjectCount: "~6B transaction rows + 12M case artifacts", queryConcurrency: "250 concurrent analyst/system sessions", modelSize: "8B-13B reasoning assistant + anomaly models", gpuRequirement: "GPU inference tier for scoring and summarization; elasticity required", retentionPeriod: "7 years", haDrRequirements: "Active-active scoring endpoints; cross-region replication for governed case data", preferredVendors: "NVIDIA-enabled compute stack, high-performance data platform, governance-integrated vector tooling", budgetTimeline: "Pilot in 6-10 weeks, production controls phased over 2 quarters" },
  },
  risk: {
    processImproved: "Portfolio stress testing and capital planning scenario runs.",
    successCriteria: "Cut scenario turnaround from days to hours and improve reproducibility/audit evidence.",
    aiPattern: "Analytics / ML pipeline",
    dataTypes: ["structured", "batch", "semi-structured"],
    dataSizeRange: "140-220 TB multi-year risk, positions, and market history",
    dailyIngestRange: "0.4-0.9 TB/day baseline; quarterly bulk refresh spikes",
    filePattern: "Large columnar datasets + scenario output objects and model artifacts",
    freshnessRequirement: "Intraday for select risk factors; end-of-day for full portfolio refresh",
    performanceTier: "intraday",
    queryConcurrency: "120 modelers, quants, and batch scenario jobs",
    gpuDependency: "Medium",
    latencyRequirement: "Interactive slices in <5 seconds; full stress runs in scheduled windows",
    dataSensitivity: "High",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Regional",
    retention: "7-10 years for model lineage and regulatory replay",
    explainability: "Required",
    accessControls: "RBAC + model-governance policy controls",
    sizingInputs: { exactDataVolume: "180 TB governed risk corpus", dailyIngestRate: "0.4-0.9 TB/day", fileObjectCount: "~900 million records + 55 million scenario output objects", queryConcurrency: "120 concurrent users/jobs", modelSize: "Ensemble risk models + optional 7B assistant for narrative analysis", gpuRequirement: "GPU pool used for acceleration where beneficial; exact count depends on run windows", retentionPeriod: "7-10 years", haDrRequirements: "Primary risk data mirrored across sites; scenario scratch recoverable from source", preferredVendors: "Accelerated compute stack, high-throughput shared data platform, governed analytics tooling", budgetTimeline: "8-12 week acceleration pilot, phased production by stress-cycle milestones" },
  },
  trading: {
    processImproved: "Research iteration, backtesting, and signal validation for intraday strategies.",
    successCriteria: "Increase backtest throughput 3x and lower research data wait time under 1 second for hot datasets.",
    aiPattern: "Analytics / ML pipeline",
    dataTypes: ["structured", "streaming", "batch"],
    dataSizeRange: "90-160 TB active market and alternative data history",
    dailyIngestRange: "1-3 TB/day with market-open burst traffic",
    filePattern: "Time-series ticks/bars plus feature-store snapshots and backtest outputs",
    freshnessRequirement: "Sub-minute ingest for market feeds; intraday feature refresh",
    performanceTier: "real-time",
    queryConcurrency: "300+ researchers, notebooks, and backtest workers",
    gpuDependency: "Medium",
    latencyRequirement: "<100 ms for hot time-series reads; <1 second for feature retrieval",
    dataSensitivity: "High",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Regional",
    retention: "5-7 years for strategy replay and controls",
    explainability: "Preferred",
    accessControls: "Desk-level RBAC + ABAC for strategy datasets",
    sizingInputs: { exactDataVolume: "125 TB active quant corpus + 30 TB historical tier", dailyIngestRate: "1-3 TB/day", fileObjectCount: "~15 billion time-series records + 25 million artifacts", queryConcurrency: "300+ concurrent users/jobs", modelSize: "Classical ML + 7B-13B research copilots", gpuRequirement: "GPU acceleration needed for feature/model cycles; pool size depends on strategy cadence", retentionPeriod: "5-7 years", haDrRequirements: "Low-latency primary site with warm DR and replicated research metadata", preferredVendors: "High-speed storage/data platform, low-latency networking, GPU-enabled analytics stack", budgetTimeline: "Initial benchmark in 6-8 weeks, production wave by desk priority" },
  },
  compliance: {
    processImproved: "Reviewing policies/regulations and mapping obligations to internal controls.",
    successCriteria: "Reduce manual review effort by 40% and provide citation-backed explainability for every answer.",
    aiPattern: "RAG",
    dataTypes: ["unstructured", "semi-structured", "batch"],
    dataSizeRange: "30-55 TB of policies, communications, controls evidence, and historical cases",
    dailyIngestRange: "150-400 GB/day plus monthly bulk updates",
    filePattern: "Millions of small/mid-size documents with chunked embeddings",
    freshnessRequirement: "Daily updates with urgent policy changes within 1 hour",
    performanceTier: "near real-time",
    queryConcurrency: "180 compliance analysts and workflow bots",
    gpuDependency: "Medium",
    latencyRequirement: "<2 seconds for retrieval and evidence-grounded response generation",
    dataSensitivity: "Regulated / Highly sensitive",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Local",
    retention: "7+ years with immutable evidence trail",
    explainability: "Required",
    accessControls: "RBAC + ABAC with legal hold segregation",
    sizingInputs: { exactDataVolume: "42 TB governed corpus", dailyIngestRate: "150-400 GB/day", fileObjectCount: "~28 million documents/objects after chunking", queryConcurrency: "180 concurrent analyst and bot sessions", modelSize: "8B-34B model with retrieval grounding", gpuRequirement: "GPU-backed embedding and inference tiers; right-size after latency benchmarks", retentionPeriod: "7+ years", haDrRequirements: "Governed content replicated cross-site; audit logs immutable and recoverable", preferredVendors: "NVIDIA-capable AI stack, secure high-performance data platform, policy-aware retrieval tooling", budgetTimeline: "Proof of value in 8 weeks, phased deployment by regulatory domain" },
  },
  "fsi-rag": {
    processImproved: "Answering internal knowledge questions for relationship managers and operations teams.",
    successCriteria: "Improve first-response quality and reduce manual search time by 50%.",
    aiPattern: "RAG",
    dataTypes: ["unstructured", "semi-structured", "batch"],
    dataSizeRange: "18-35 TB knowledge corpus across manuals, FAQs, product docs, and case notes",
    dailyIngestRange: "80-250 GB/day incremental updates",
    filePattern: "High count of small documents with frequent metadata updates",
    freshnessRequirement: "Incremental updates every 15-60 minutes for critical sources",
    performanceTier: "near real-time",
    queryConcurrency: "400 frontline users during business hours",
    gpuDependency: "Medium",
    latencyRequirement: "<1.5 seconds median answer latency",
    dataSensitivity: "High",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Regional",
    retention: "5-7 years based on policy class",
    explainability: "Required",
    accessControls: "RBAC + ABAC by team, account, and sensitivity label",
    sizingInputs: { exactDataVolume: "24 TB active knowledge store + 8 TB archive", dailyIngestRate: "80-250 GB/day", fileObjectCount: "~22 million docs/chunks", queryConcurrency: "400 concurrent users", modelSize: "7B-13B retrieval assistant", gpuRequirement: "GPU inference pool required for interactive responses; exact scale depends on peak QPS", retentionPeriod: "5-7 years", haDrRequirements: "Primary retrieval services HA; metadata and index replication to DR", preferredVendors: "Accelerated inference stack, scalable vector/search layer, governance-first data platform", budgetTimeline: "Pilot in 6-8 weeks; production expansion tied to user adoption and quality targets" },
  },
  "fsi-ft": {
    processImproved: "Adapting domain models for financial language, client operations, and risk narratives.",
    successCriteria: "Reach target quality thresholds for domain tasks while maintaining governed reproducibility.",
    aiPattern: "Fine-tuning",
    dataTypes: ["structured", "unstructured", "semi-structured", "batch"],
    dataSizeRange: "120 TB curated training corpus + 25 TB validation/test data",
    dailyIngestRange: "2-5 TB/day new or updated domain data",
    filePattern: "~40 million documents/objects after chunking and curation",
    freshnessRequirement: "Weekly-to-monthly retraining with fast patch cycles for priority policies",
    performanceTier: "batch/end-of-day",
    queryConcurrency: "50 internal researchers / batch evaluation jobs",
    gpuDependency: "High",
    latencyRequirement: "Training throughput optimized for scheduled windows; evaluation response <10 seconds",
    dataSensitivity: "Regulated / Highly sensitive",
    auditTrail: "Strict",
    encryption: "Required",
    dataResidency: "Regional",
    retention: "7 years for governed datasets and experiment artifacts",
    explainability: "Required",
    accessControls: "RBAC + ABAC with project and dataset segmentation",
    sizingInputs: { exactDataVolume: "120 TB curated training corpus + 25 TB validation/test data", dailyIngestRate: "2-5 TB/day new or updated domain data", fileObjectCount: "~40 million documents/objects after chunking and curation", queryConcurrency: "50 internal researchers / batch evaluation jobs", modelSize: "7B-70B parameter open-weight model; LoRA/QLoRA fine-tuning initially", gpuRequirement: "GPU pool required; exact count depends on model size, batch size, and training window", retentionPeriod: "7 years for governed datasets and experiment artifacts", haDrRequirements: "Production registry and governed datasets replicated; training scratch tier recoverable from source", preferredVendors: "NVIDIA GPU stack, high-performance data platform, vector/model registry tooling", budgetTimeline: "Pilot in 8-12 weeks; phased production expansion after benchmark" },
  },
  "ai-training": { processImproved: "Training large domain or foundation models with distributed data prep and checkpointing.", successCriteria: "Sustain high GPU utilization and finish targeted training runs within planned windows.", aiPattern: "Training from scratch", dataTypes: ["unstructured", "structured", "batch"], dataSizeRange: "0.5-1.5 PB training corpus potential", dailyIngestRange: "5-20 TB/day preprocessing and refresh", filePattern: "Billions of tokens/files with heavy checkpoint and artifact output", freshnessRequirement: "Batch refresh aligned to training milestones", performanceTier: "batch/end-of-day", queryConcurrency: "Large distributed jobs + 40-80 researchers", gpuDependency: "High", latencyRequirement: "Throughput-first; checkpoint read/write consistency is critical", dataSensitivity: "High", auditTrail: "Strict", encryption: "Required", dataResidency: "Regional", retention: "3-7 years for datasets, checkpoints, and lineage", explainability: "Preferred", accessControls: "Project-level RBAC with dataset policy gates", sizingInputs: { exactDataVolume: "Illustrative starting point: 800 TB active corpus + expandable archive tier", dailyIngestRate: "5-20 TB/day", fileObjectCount: "Hundreds of millions to billions of files/objects", queryConcurrency: "Distributed training pipelines + 40-80 concurrent researchers", modelSize: "Multi-billion to hundred-billion parameter model programs", gpuRequirement: "Large GPU pool required; exact count depends on model target and training SLA", retentionPeriod: "3-7 years", haDrRequirements: "Checkpoint and registry replication required; scratch can be rehydrated", preferredVendors: "NVIDIA accelerator ecosystem, high-throughput training data platform, orchestration/registry tooling", budgetTimeline: "90-day benchmark phase followed by staged production clusters" } },
  inference: { processImproved: "Serving LLM and ML inference APIs with predictable latency and safety controls.", successCriteria: "Meet p95 latency SLO and maintain response quality under peak concurrency.", aiPattern: "Inference only", dataTypes: ["structured", "unstructured", "streaming"], dataSizeRange: "20-60 TB model artifacts, prompts/features, and session context", dailyIngestRange: "200 GB-1 TB/day logs, prompts, and retrieval context updates", filePattern: "High request volume with mixed small objects and cache entries", freshnessRequirement: "Minute-level model/config rollout and guardrail updates", performanceTier: "real-time", queryConcurrency: "1,500-5,000 concurrent requests depending on channel", gpuDependency: "High", latencyRequirement: "p95 <500 ms for core API paths; strict tail-latency controls", dataSensitivity: "High", auditTrail: "Strict", encryption: "Required", dataResidency: "Global", retention: "13-24 months serving telemetry; longer for regulated channels", explainability: "Preferred", accessControls: "Token-based auth + RBAC policy controls", sizingInputs: { exactDataVolume: "35 TB active serving + context data", dailyIngestRate: "200 GB-1 TB/day", fileObjectCount: "~150 million objects including cache/session artifacts", queryConcurrency: "1,500-5,000 concurrent requests", modelSize: "7B-70B serving mix (quantized and full precision tiers)", gpuRequirement: "GPU serving pool required; exact count depends on latency SLO and throughput target", retentionPeriod: "13-24 months baseline telemetry retention", haDrRequirements: "Multi-zone serving HA with failover; config/model registry replicated", preferredVendors: "NVIDIA inference stack, high-performance data/cache platform, observability + guardrail tooling", budgetTimeline: "SLO pilot in 6-8 weeks, production hardening in phased releases" } },
  simulation: { processImproved: "Running simulation campaigns with scheduler orchestration and faster post-processing.", successCriteria: "Increase completed simulation jobs per cycle and shorten result-to-insight time.", aiPattern: "HPC simulation", dataTypes: ["structured", "batch"], dataSizeRange: "250-600 TB active simulation datasets and outputs", dailyIngestRange: "1-4 TB/day inputs; output bursts during run completions", filePattern: "Large parallel files plus derived visualization artifacts", freshnessRequirement: "Job-cycle driven; rapid access after run completion", performanceTier: "batch/end-of-day", queryConcurrency: "500+ parallel jobs plus analyst post-processing sessions", gpuDependency: "Medium", latencyRequirement: "Low-latency parallel I/O for checkpoints and solver outputs", dataSensitivity: "Moderate", auditTrail: "Baseline", encryption: "Required", dataResidency: "Regional", retention: "3-5 years for reproducibility and publication support", explainability: "Not required", accessControls: "Project/workgroup RBAC", sizingInputs: { exactDataVolume: "400 TB active working set", dailyIngestRate: "1-4 TB/day", fileObjectCount: "~80 million files/objects", queryConcurrency: "500+ parallel jobs", modelSize: "Simulation/solver models + optional surrogate AI models", gpuRequirement: "GPU acceleration for selected solvers/AI surrogates; exact count workload-dependent", retentionPeriod: "3-5 years", haDrRequirements: "Core project data replicated; intermediate scratch reproducible from job inputs", preferredVendors: "HPC scheduler ecosystem, parallel file/data platform, accelerated compute stack", budgetTimeline: "12-week architecture/benchmark sprint, phased deployment by simulation program" } },
  genomics: { processImproved: "Scaling sequencing pipelines and downstream AI-assisted variant interpretation.", successCriteria: "Cut sample turnaround time while preserving regulated traceability and reproducibility.", aiPattern: "Analytics / ML pipeline", dataTypes: ["unstructured", "structured", "batch"], dataSizeRange: "120-300 TB active genomic data plus long-term archive", dailyIngestRange: "0.5-2 TB/day from sequencers and pipeline outputs", filePattern: "Very high count of small/medium files with metadata-heavy workflow states", freshnessRequirement: "Daily ingest; priority clinical cohorts processed same day", performanceTier: "intraday", queryConcurrency: "200 pipeline tasks + 60 analysts/scientists", gpuDependency: "Medium", latencyRequirement: "Fast metadata and file-open performance for pipeline stages", dataSensitivity: "Regulated / Highly sensitive", auditTrail: "Strict", encryption: "Required", dataResidency: "Local", retention: "10+ years for reproducibility and regulated records", explainability: "Required", accessControls: "RBAC + cohort/consent-aware ABAC", sizingInputs: { exactDataVolume: "180 TB active + expandable long-term archive", dailyIngestRate: "0.5-2 TB/day", fileObjectCount: "300+ million files/objects across pipeline stages", queryConcurrency: "200 pipeline tasks + 60 users", modelSize: "Domain ML models + optional 7B-13B assistant for interpretation workflows", gpuRequirement: "GPU pool for select analysis/inference; exact count depends on sample throughput", retentionPeriod: "10+ years", haDrRequirements: "Clinical/regulatory data replicated; staging tiers recoverable from authoritative source", preferredVendors: "Regulated-ready data platform, accelerated analytics compute, workflow orchestration tooling", budgetTimeline: "8-12 week pilot for key pipeline stages, then phased lab-wide rollout" } },
  media: { processImproved: "Coordinating rendering, enhancement, and delivery workflows under deadline pressure.", successCriteria: "Increase render throughput and hit delivery deadlines during peak ingest windows.", aiPattern: "Inference only", dataTypes: ["unstructured", "structured", "batch", "streaming"], dataSizeRange: "200-500 TB active media assets and render outputs", dailyIngestRange: "2-8 TB/day with production burst events", filePattern: "Mixed large video/image files plus many small sidecar metadata objects", freshnessRequirement: "Hourly ingest/index updates during production cycles", performanceTier: "near real-time", queryConcurrency: "400 creative users + 1,000 render/inference jobs", gpuDependency: "High", latencyRequirement: "Fast asset retrieval and queue response; render windows measured in minutes", dataSensitivity: "Moderate", auditTrail: "Baseline", encryption: "Required", dataResidency: "Global", retention: "2-5 years active, longer archive for key assets", explainability: "Not required", accessControls: "Project RBAC with partner-limited access", sizingInputs: { exactDataVolume: "320 TB active asset store", dailyIngestRate: "2-8 TB/day", fileObjectCount: "~95 million files/objects", queryConcurrency: "400 users + 1,000 jobs", modelSize: "Vision/audio models from 1B-34B plus render models", gpuRequirement: "GPU render/inference pool required; exact count depends on delivery windows", retentionPeriod: "2-5 years active plus archive policy", haDrRequirements: "Primary production tier HA; project archives replicated to DR", preferredVendors: "NVIDIA-enabled render/inference stack, high-throughput shared data platform, media workflow tooling", budgetTimeline: "6-week pilot for one production line, expansion by release calendar" } },
  custom: { workloadName: "Custom AI workload example", processImproved: "Improving a high-value decision workflow with AI-assisted retrieval and analytics.", successCriteria: "Define measurable baseline improvements and a scoped pilot plan with governance controls.", aiPattern: "Analytics / ML pipeline", dataTypes: ["structured", "unstructured", "batch"], dataSizeRange: "10-40 TB starting dataset with growth expected", dailyIngestRange: "100-500 GB/day", filePattern: "Mixed document and tabular objects with moderate metadata growth", freshnessRequirement: "Daily refresh with optional intraday updates for priority sources", performanceTier: "near real-time", queryConcurrency: "50-150 users/jobs", gpuDependency: "Medium", latencyRequirement: "<2 seconds for interactive queries where feasible", dataSensitivity: "High", auditTrail: "Strict", encryption: "Required", dataResidency: "Regional", retention: "3-7 years based on policy", explainability: "Required", accessControls: "RBAC + ABAC", sizingInputs: { exactDataVolume: "Illustrative: 20 TB initial corpus", dailyIngestRate: "100-500 GB/day", fileObjectCount: "~5-20 million objects", queryConcurrency: "50-150 concurrent users/jobs", modelSize: "7B-13B model family to start", gpuRequirement: "GPU pool likely required; final count depends on latency and throughput needs", retentionPeriod: "3-7 years", haDrRequirements: "Replicate governed datasets and critical services; define RPO/RTO during design", preferredVendors: "Accelerated compute stack, scalable data platform, governance and MLOps tooling", budgetTimeline: "4-8 week discovery + pilot design phase" } },
};
