"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RAW_CATALOG_SOURCE_PACKS = exports.DEFAULT_PACK_ORDER = void 0;
exports.DEFAULT_PACK_ORDER = [
    "solutions-architecture",
    "sales-engineering",
    "customer-success-tam",
    "partner-channel",
    "infrastructure-cloud-platform",
    "storage-data-protection",
];
exports.RAW_CATALOG_SOURCE_PACKS = [
    {
        id: "solutions-architecture",
        label: "Solutions Architecture",
        description: "Customer-facing architecture roles across cloud, data, and enterprise platforms.",
        roleKeywords: [
            "solutions architect",
            "solution architect",
            "partner solutions architect",
            "customer architect",
            "enterprise architect",
            "technical architect",
        ],
        sources: [
            { company: "Snowflake", boardType: "lever", boardToken: "snowflake" },
            { company: "Confluent", boardType: "lever", boardToken: "confluent" },
            { company: "Databricks", boardType: "lever", boardToken: "databricks" },
            { company: "Nutanix", boardType: "greenhouse", boardToken: "nutanix" },
            { company: "Cloudflare", boardType: "lever", boardToken: "cloudflare" },
            { company: "ServiceNow", boardType: "smartrecruiters", boardToken: "servicenow" },
            { company: "New Relic", boardType: "lever", boardToken: "newrelic" },
            { company: "Atlassian", boardType: "greenhouse", boardToken: "atlassian" },
            { company: "Twilio", boardType: "greenhouse", boardToken: "twilio" },
            { company: "Grafana Labs", boardType: "greenhouse", boardToken: "grafanalabs" },
            { company: "Samsara", boardType: "lever", boardToken: "samsara" },
        ],
    },
    {
        id: "sales-engineering",
        label: "Sales Engineering",
        description: "Pre-sales engineering and field technical roles aligned to solution selling.",
        roleKeywords: [
            "sales engineer",
            "solutions engineer",
            "solution engineer",
            "pre-sales",
            "presales",
            "demo",
            "proof of concept",
            "poc",
        ],
        sources: [
            { company: "MongoDB", boardType: "greenhouse", boardToken: "mongodb" },
            { company: "GitLab", boardType: "greenhouse", boardToken: "gitlab" },
            { company: "HashiCorp", boardType: "greenhouse", boardToken: "hashicorp" },
            { company: "Elastic", boardType: "smartrecruiters", boardToken: "elastic" },
            { company: "Clari", boardType: "ashby", boardToken: "clari" },
            { company: "Datadog", boardType: "greenhouse", boardToken: "datadoghq" },
            { company: "Palo Alto Networks", boardType: "lever", boardToken: "paloaltonetworks" },
            { company: "CrowdStrike", boardType: "greenhouse", boardToken: "crowdstrike" },
            { company: "Dynatrace", boardType: "greenhouse", boardToken: "dynatrace" },
            { company: "Snyk", boardType: "greenhouse", boardToken: "snyk" },
            { company: "Netskope", boardType: "greenhouse", boardToken: "netskope" },
        ],
    },
    {
        id: "customer-success-tam",
        label: "Customer Success + TAM",
        description: "Technical account management, post-sales, adoption, and success engineering roles.",
        roleKeywords: [
            "technical account manager",
            "account manager",
            "tam",
            "customer success",
            "customer engineer",
            "post-sales",
            "post sales",
            "implementation",
            "adoption",
        ],
        sources: [
            { company: "Okta", boardType: "greenhouse", boardToken: "okta" },
            { company: "HubSpot", boardType: "greenhouse", boardToken: "hubspot" },
            { company: "Miro", boardType: "greenhouse", boardToken: "miro" },
            { company: "Braze", boardType: "greenhouse", boardToken: "braze" },
            { company: "Cockroach Labs", boardType: "greenhouse", boardToken: "cockroachlabs" },
            { company: "PagerDuty", boardType: "greenhouse", boardToken: "pagerduty" },
            { company: "LaunchDarkly", boardType: "greenhouse", boardToken: "launchdarkly" },
            { company: "Box", boardType: "greenhouse", boardToken: "boxinc" },
            { company: "Smartsheet", boardType: "greenhouse", boardToken: "smartsheet" },
            { company: "Airtable", boardType: "greenhouse", boardToken: "airtable" },
            { company: "Fivetran", boardType: "greenhouse", boardToken: "fivetran" },
        ],
    },
    {
        id: "partner-channel",
        label: "Partner + Channel",
        description: "Alliances, channel, partner enablement, and ecosystem-facing roles.",
        roleKeywords: [
            "partner",
            "channel",
            "alliances",
            "ecosystem",
            "gsi",
            "reseller",
            "enablement",
        ],
        sources: [
            { company: "Palo Alto Networks", boardType: "lever", boardToken: "paloaltonetworks" },
            { company: "Zscaler", boardType: "lever", boardToken: "zscaler" },
            { company: "Snyk", boardType: "greenhouse", boardToken: "snyk" },
            { company: "SentinelOne", boardType: "lever", boardToken: "sentinelone" },
            { company: "Databricks", boardType: "lever", boardToken: "databricks" },
            { company: "Snowflake", boardType: "lever", boardToken: "snowflake" },
            { company: "Confluent", boardType: "lever", boardToken: "confluent" },
            { company: "Cloudflare", boardType: "lever", boardToken: "cloudflare" },
            { company: "Nutanix", boardType: "greenhouse", boardToken: "nutanix" },
            { company: "GitLab", boardType: "greenhouse", boardToken: "gitlab" },
        ],
    },
    {
        id: "infrastructure-cloud-platform",
        label: "Infrastructure + Cloud Platform",
        description: "Infrastructure, cloud platform, virtualization, and datacenter-oriented employers.",
        roleKeywords: [
            "infrastructure",
            "cloud",
            "platform",
            "kubernetes",
            "devops",
            "virtualization",
            "vmware",
            "datacenter",
            "migration",
            "hybrid cloud",
        ],
        sources: [
            { company: "Vultr", boardType: "greenhouse", boardToken: "vultr" },
            { company: "DigitalOcean", boardType: "greenhouse", boardToken: "digitalocean98" },
            { company: "Akamai", boardType: "smartrecruiters", boardToken: "akamai" },
            { company: "Nerdio", boardType: "ashby", boardToken: "nerdio" },
            { company: "Fastly", boardType: "greenhouse", boardToken: "fastly" },
            { company: "CloudBees", boardType: "greenhouse", boardToken: "cloudbees" },
            { company: "Platform9", boardType: "greenhouse", boardToken: "platform9" },
            { company: "Mirantis", boardType: "greenhouse", boardToken: "mirantis" },
            { company: "Red Hat", boardType: "smartrecruiters", boardToken: "redhat" },
            { company: "SUSE", boardType: "lever", boardToken: "suse" },
            { company: "Canonical", boardType: "greenhouse", boardToken: "canonical" },
        ],
    },
    {
        id: "storage-data-protection",
        label: "Storage + Data Protection",
        description: "Storage, backup, recovery, and data protection vendors aligned to James's background.",
        roleKeywords: [
            "storage",
            "backup",
            "recovery",
            "data protection",
            "data resiliency",
            "disaster recovery",
            "replication",
        ],
        sources: [
            { company: "Rubrik", boardType: "greenhouse", boardToken: "rubrik" },
            { company: "Cohesity", boardType: "greenhouse", boardToken: "cohesity" },
            { company: "Pure Storage", boardType: "greenhouse", boardToken: "purestorage" },
            { company: "Veeam", boardType: "smartrecruiters", boardToken: "veeamsoftware" },
            { company: "Wasabi Technologies", boardType: "greenhouse", boardToken: "wasabi" },
            { company: "N-able", boardType: "greenhouse", boardToken: "nable" },
            { company: "Druva", boardType: "greenhouse", boardToken: "druva" },
            { company: "Commvault", boardType: "smartrecruiters", boardToken: "commvault" },
            { company: "Backblaze", boardType: "greenhouse", boardToken: "backblaze" },
            { company: "Infinidat", boardType: "greenhouse", boardToken: "infinidat" },
            { company: "Nasuni", boardType: "greenhouse", boardToken: "nasuni" },
        ],
    },
];
