import type { AiFactoryEconomicsMockDashboard } from "./types";

export const aiFactoryEconomicsMockDashboard: AiFactoryEconomicsMockDashboard = {
  scenarioName: "Local workstation inference economics demo",
  summary:
    "A Phase 3 dashboard that keeps demo/mock economics visible while running local Ollama prompts through a streaming proxy.",
  assumptions: [
    {
      id: "energy-rate",
      label: "Energy rate assumption",
      value: "$0.16/kWh",
      classification: "Configured",
      description: "Static display assumption only; not used by a live collector in Phase 3.",
      tone: "info",
    },
    {
      id: "demo-mode",
      label: "Demo mode",
      value: "On",
      classification: "Configured",
      description: "Phase 3 renders demo/mock economics plus optional local Ollama health, model discovery, and prompt streaming.",
      tone: "good",
    },
  ],
  metrics: [
    {
      id: "selected-model",
      label: "Selected model",
      value: "llama3.1:8b-instruct",
      classification: "Demo/mock",
      description: "Placeholder model name for demo fallback; discovered local Ollama models and prompt streams are shown separately as Measured in Phase 3.",
      tone: "info",
    },
    {
      id: "ttft",
      label: "Time to first token",
      value: "420 ms",
      classification: "Demo/mock",
      description: "Mock first-token timing for the dashboard shell; Phase 3 streams responses but does not calculate official TTFT.",
      tone: "good",
    },
    {
      id: "total-latency",
      label: "Total latency",
      value: "2.8 s",
      classification: "Demo/mock",
      description: "Mock end-to-end economics placeholder; Phase 3 does not calculate official total latency metrics from runs.",
      tone: "good",
    },
    {
      id: "tokens-sec",
      label: "Estimated tokens/sec",
      value: "31.4 tok/s",
      classification: "Demo/mock",
      description: "Mock throughput preview; later phases will clearly separate measured timing from estimated token counts.",
      tone: "info",
    },
    {
      id: "gpu-utilization",
      label: "GPU utilization",
      value: "68%",
      classification: "Demo/mock",
      description: "Mock GPU utilization; Phase 3 does not call nvidia-smi or sample hardware telemetry.",
      tone: "info",
    },
    {
      id: "gpu-memory",
      label: "GPU memory",
      value: "4.8 / 6 GB",
      classification: "Demo/mock",
      description: "Mock memory pressure preview aligned to the local 6 GB laptop GPU demo target until live telemetry replaces it.",
      tone: "info",
    },
    {
      id: "gpu-watts",
      label: "GPU watts",
      value: "146 W",
      classification: "Demo/mock",
      description: "Mock power draw; no local process or hardware probe is used in Phase 3.",
      tone: "warning",
    },
    {
      id: "gpu-temperature",
      label: "GPU temperature",
      value: "62°C",
      classification: "Demo/mock",
      description: "Mock thermal signal for future local NVIDIA telemetry.",
      tone: "info",
    },
    {
      id: "tokens-per-watt",
      label: "Estimated tokens per watt",
      value: "0.22 tok/W",
      classification: "Demo/mock",
      description: "Mock efficiency preview; later phases will explain whether watts are sampled, measured, or unavailable.",
      tone: "good",
    },
    {
      id: "cost-per-run",
      label: "Estimated cost per run",
      value: "$0.000018",
      classification: "Demo/mock",
      description: "Mock economics preview using a static energy-rate assumption; no persisted cost model exists in Phase 3.",
      tone: "good",
    },
  ],
  readiness: [
    {
      title: "Ollama",
      status: "Checked",
      classification: "Measured",
      description: "Phase 3 checks local Ollama health, discovers /api/tags models, and runs local prompt streams with graceful fallback when unavailable.",
    },
    {
      title: "NVIDIA telemetry",
      status: "Planned",
      classification: "Demo/mock",
      description: "Planned for Phase 5; Phase 3 does not call nvidia-smi.",
    },
    {
      title: "Run history",
      status: "Not persistent",
      classification: "Demo/mock",
      description: "Planned as in-memory summaries first; no database or persistent storage is added in Phase 3.",
    },
  ],
  phases: [
    {
      phase: "Phase 1",
      title: "Static shell",
      status: "Complete",
      description: "Dashboard shell, local-only copy, mock metrics, readiness guidance, and documentation updates.",
    },
    {
      phase: "Phase 3",
      title: "Ollama health/model discovery",
      status: "Complete",
      description: "Local health checks and model list discovery while retaining demo fallback behavior.",
    },
    {
      phase: "Phase 3",
      title: "Prompt runner",
      status: "Active",
      description: "Run local Ollama prompts and stream responses without persisting prompt or response content; official metrics wait for Phase 4.",
      active: true,
    },
    {
      phase: "Phase 5",
      title: "NVIDIA telemetry",
      status: "Later",
      description: "Sample local GPU utilization, memory, watts, and temperature when nvidia-smi is available.",
    },
  ],
};
