import type { AiFactoryEconomicsMockDashboard } from "./types";

export const aiFactoryEconomicsMockDashboard: AiFactoryEconomicsMockDashboard = {
  scenarioName: "Local workstation inference economics demo",
  summary:
    "A static Phase 1 dashboard that previews how local model latency, GPU telemetry, throughput, power, and per-run cost will be explained in later phases.",
  assumptions: [
    {
      id: "energy-rate",
      label: "Energy rate assumption",
      value: "$0.16/kWh",
      classification: "Configured",
      description: "Static display assumption only; not used by a live collector in Phase 1.",
      tone: "info",
    },
    {
      id: "demo-mode",
      label: "Demo mode",
      value: "On",
      classification: "Configured",
      description: "Phase 1 intentionally renders without local services, storage, or hardware probes.",
      tone: "good",
    },
  ],
  metrics: [
    {
      id: "selected-model",
      label: "Selected model",
      value: "llama3.1:8b-instruct",
      classification: "Demo/mock",
      description: "Placeholder model name; no Ollama discovery or local model validation runs in Phase 1.",
      tone: "info",
    },
    {
      id: "ttft",
      label: "Time to first token",
      value: "420 ms",
      classification: "Demo/mock",
      description: "Mock first-token timing for the dashboard shell; streaming is planned for a later phase.",
      tone: "good",
    },
    {
      id: "total-latency",
      label: "Total latency",
      value: "2.8 s",
      classification: "Demo/mock",
      description: "Mock end-to-end run duration; no real prompt execution happens in Phase 1.",
      tone: "good",
    },
    {
      id: "tokens-sec",
      label: "Estimated tokens/sec",
      value: "31.4 tok/s",
      classification: "Demo/mock",
      description: "Mock throughput preview; later phases will clearly separate measured timing from estimated token counts.",
      tone: "info",
    },
    {
      id: "gpu-utilization",
      label: "GPU utilization",
      value: "68%",
      classification: "Demo/mock",
      description: "Mock GPU utilization; Phase 1 does not call nvidia-smi or sample hardware telemetry.",
      tone: "info",
    },
    {
      id: "gpu-memory",
      label: "GPU memory",
      value: "9.7 / 16 GB",
      classification: "Demo/mock",
      description: "Mock memory pressure preview for future NVIDIA telemetry panels.",
      tone: "info",
    },
    {
      id: "gpu-watts",
      label: "GPU watts",
      value: "146 W",
      classification: "Demo/mock",
      description: "Mock power draw; no local process or hardware probe is used in Phase 1.",
      tone: "warning",
    },
    {
      id: "gpu-temperature",
      label: "GPU temperature",
      value: "62°C",
      classification: "Demo/mock",
      description: "Mock thermal signal for future local NVIDIA telemetry.",
      tone: "info",
    },
    {
      id: "tokens-per-watt",
      label: "Estimated tokens per watt",
      value: "0.22 tok/W",
      classification: "Demo/mock",
      description: "Mock efficiency preview; later phases will explain whether watts are sampled, measured, or unavailable.",
      tone: "good",
    },
    {
      id: "cost-per-run",
      label: "Estimated cost per run",
      value: "$0.000018",
      classification: "Demo/mock",
      description: "Mock economics preview using a static energy-rate assumption; no persisted cost model exists in Phase 1.",
      tone: "good",
    },
  ],
  readiness: [
    {
      title: "Ollama",
      status: "Planned",
      classification: "Demo/mock",
      description: "Planned for Phase 2 health checks and model discovery; not connected in Phase 1.",
    },
    {
      title: "NVIDIA telemetry",
      status: "Planned",
      classification: "Demo/mock",
      description: "Planned for Phase 5; this shell does not call nvidia-smi.",
    },
    {
      title: "Run history",
      status: "Not persistent",
      classification: "Demo/mock",
      description: "Planned as in-memory summaries first; no database or persistent storage is added in Phase 1.",
    },
  ],
  phases: [
    {
      phase: "Phase 1",
      title: "Static shell",
      status: "Active",
      description: "Dashboard shell, local-only copy, mock metrics, readiness guidance, and documentation updates.",
      active: true,
    },
    {
      phase: "Phase 2",
      title: "Ollama health/model discovery",
      status: "Next",
      description: "Add local health checks and model list discovery while retaining demo fallback behavior.",
    },
    {
      phase: "Phase 3",
      title: "Prompt runner",
      status: "Later",
      description: "Introduce prompt execution and latency timing without persisting prompt content.",
    },
    {
      phase: "Phase 5",
      title: "NVIDIA telemetry",
      status: "Later",
      description: "Sample local GPU utilization, memory, watts, and temperature when nvidia-smi is available.",
    },
  ],
};
