import type { HpcLabConcept, HpcLabConceptId } from "./types";

const CONCEPTS: Record<HpcLabConceptId, HpcLabConcept> = {
  "compute-nodes": {
    id: "compute-nodes",
    category: "control",
    label: "Compute nodes",
    hoverTitle: "CPU compute clients",
    explanation: "CPU-oriented cluster nodes that run jobs and generate storage/network demand.",
    realWorldMapping: "Maps to Lustre client-side compute hosts in a higher-ed HPC cluster.",
    whyItMatters: "This sets compute supply. It is not the shared filesystem itself.",
    modeledToday: true,
  },
  "gpu-nodes": {
    id: "gpu-nodes",
    category: "control",
    label: "GPU nodes",
    hoverTitle: "GPU compute clients",
    explanation: "GPU-oriented compute clients used for distributed AI and accelerator-heavy phases.",
    realWorldMapping: "Maps to GPU client nodes that rely on shared parallel storage for data feed and checkpoints.",
    whyItMatters: "More GPU clients can increase I/O demand and expose storage or network pressure.",
    modeledToday: true,
  },
  "oss-count": {
    id: "oss-count",
    category: "control",
    label: "OSS count",
    hoverTitle: "Shared data-service fanout",
    explanation: "Number of shared storage service endpoints in the simulated parallel data layer.",
    realWorldMapping: "Directional analogue to Lustre OSS service fanout that widens the shared data path.",
    whyItMatters: "More OSS usually increases aggregate data-path width and sustained throughput headroom.",
    modeledToday: true,
  },
  "ost-per-oss": {
    id: "ost-per-oss",
    category: "control",
    label: "OST per OSS",
    hoverTitle: "Striped target inventory",
    explanation: "Number of object targets behind each storage service endpoint.",
    realWorldMapping: "Maps to OST inventory behind OSS services in a Lustre-style deployment.",
    whyItMatters: "More targets can increase aggregate striped capacity and reduce hotspotting risk.",
    modeledToday: true,
  },
  "stripe-width": {
    id: "stripe-width",
    category: "control",
    label: "Stripe width",
    hoverTitle: "File layout width",
    explanation: "How many OSTs a file layout spans in the shared filesystem model.",
    realWorldMapping: "Directional mapping to Lustre striping policy across OSTs.",
    whyItMatters: "Helps sequential shared-filesystem throughput but does not solve every bottleneck class.",
    modeledToday: true,
  },
  "metadata-latency": {
    id: "metadata-latency",
    category: "control",
    label: "Metadata latency",
    hoverTitle: "Metadata responsiveness",
    explanation: "Metadata operation response delay in the shared filesystem control path.",
    realWorldMapping: "Closest simulator analogue to metadata-service pressure on MDS/MDT-side behavior.",
    whyItMatters: "Higher latency can stall namespace-heavy workloads even when data bandwidth looks adequate.",
    modeledToday: true,
  },
  "network-bandwidth": {
    id: "network-bandwidth",
    category: "control",
    label: "Network bandwidth",
    hoverTitle: "Aggregate fabric cap",
    explanation: "Total modeled client-to-storage throughput ceiling.",
    realWorldMapping: "Maps to aggregate fabric capacity between compute clients and shared storage.",
    whyItMatters: "Network ceilings can throttle delivered throughput even if storage has spare capacity.",
    modeledToday: true,
  },
  "checkpoint-frequency": {
    id: "checkpoint-frequency",
    category: "control",
    label: "Checkpoint frequency",
    hoverTitle: "Bursty write cadence",
    explanation: "How often checkpoint phases trigger for checkpoint-capable jobs.",
    realWorldMapping: "Represents periodic save behavior common in distributed training and long HPC runs.",
    whyItMatters: "More frequent checkpoints can increase bursty writes and useful-progress pauses.",
    modeledToday: true,
  },
  "concurrent-jobs": {
    id: "concurrent-jobs",
    category: "control",
    label: "Concurrent jobs",
    hoverTitle: "Multi-tenant pressure",
    explanation: "Total workload concurrency competing for compute slots and shared storage resources.",
    realWorldMapping: "Maps to scheduler-level multi-tenant cluster pressure.",
    whyItMatters: "Higher concurrency can amplify queueing and metadata/data-path contention.",
    modeledToday: true,
  },
  "simulation-duration": {
    id: "simulation-duration",
    category: "control",
    label: "Simulation duration",
    hoverTitle: "Experiment horizon",
    explanation: "How many ticks the run lasts.",
    realWorldMapping: "Equivalent to how long you observe the synthetic scenario, not hardware inventory.",
    whyItMatters: "Longer horizons can reveal later-phase contention and additional job completions.",
    modeledToday: true,
  },
  "tick-duration": {
    id: "tick-duration",
    category: "control",
    label: "Tick duration",
    hoverTitle: "Tick time scale",
    explanation: "Seconds represented by one simulation tick.",
    realWorldMapping: "A time-resolution setting for the experiment, not a hardware property.",
    whyItMatters: "Changes interpretation granularity without changing the modeled topology itself.",
    modeledToday: true,
  },
  "cpu-pool": {
    id: "cpu-pool",
    category: "topology",
    label: "CPU pool",
    hoverTitle: "CPU client fleet",
    explanation: "CPU compute hosts that consume scheduler slots and perform job work.",
    realWorldMapping: "Maps to Lustre client nodes doing CPU-heavy batch work.",
    whyItMatters: "Compute pressure often starts here when job demand exceeds CPU capacity.",
    modeledToday: true,
  },
  "gpu-pool": {
    id: "gpu-pool",
    category: "topology",
    label: "GPU pool",
    hoverTitle: "GPU client fleet",
    explanation: "GPU compute hosts for accelerator-heavy and AI training jobs.",
    realWorldMapping: "Maps to GPU client nodes that depend on shared storage and network feed.",
    whyItMatters: "Can drive high checkpoint and streaming demand against shared infrastructure.",
    modeledToday: true,
  },
  "network-fabric": {
    id: "network-fabric",
    category: "topology",
    label: "Network fabric",
    hoverTitle: "Compute-to-storage fabric",
    explanation: "Modeled transport path carrying aggregate client read/write traffic.",
    realWorldMapping: "Directional analogue of HPC interconnect capacity used for storage traffic.",
    whyItMatters: "Fabric limits can dominate even if metadata and data services are healthy.",
    modeledToday: true,
  },
  "mds-metadata": {
    id: "mds-metadata",
    category: "topology",
    label: "MDS / metadata",
    hoverTitle: "Metadata control path",
    explanation: "Represents namespace and metadata service responsiveness.",
    realWorldMapping: "Closest concept to MDS/MDT pressure in Lustre-like systems.",
    whyItMatters: "Metadata-heavy workloads can stall here before data transfer becomes dominant.",
    modeledToday: true,
  },
  "oss-pool": {
    id: "oss-pool",
    category: "topology",
    label: "OSS pool",
    hoverTitle: "Data-service endpoints",
    explanation: "Shared data-service layer that fronts striped storage targets.",
    realWorldMapping: "Directional analogue of OSS service tier in Lustre-style environments.",
    whyItMatters: "This layer determines how wide the shared data path can scale.",
    modeledToday: true,
  },
  "total-osts": {
    id: "total-osts",
    category: "topology",
    label: "Total OSTs",
    hoverTitle: "Total striped targets",
    explanation: "Total number of object storage targets in the normalized topology.",
    realWorldMapping: "Matches the aggregate OST inventory concept used for striped layouts.",
    whyItMatters: "Constrains maximum striping fanout and aggregate data-path parallelism.",
    modeledToday: true,
  },
  "effective-stripe-width": {
    id: "effective-stripe-width",
    category: "topology",
    label: "Effective stripe width",
    hoverTitle: "Normalized striping width",
    explanation: "Stripe width after normalization against available OST inventory.",
    realWorldMapping: "Mirrors practical striping limits when requested width exceeds available targets.",
    whyItMatters: "Shows the actually used striping parallelism, not just requested settings.",
    modeledToday: true,
  },
  "wait-on-data": {
    id: "wait-on-data",
    category: "metric",
    label: "Wait on data",
    hoverTitle: "Data-wait share",
    explanation: "Share of work time where jobs wait on shared I/O progress.",
    realWorldMapping: "Directional indicator of storage/network blocking from client perspective.",
    whyItMatters: "High values suggest shared-path delivery is gating useful compute progress.",
    modeledToday: true,
  },
  "metadata-utilization": {
    id: "metadata-utilization",
    category: "metric",
    label: "Metadata utilization",
    hoverTitle: "Metadata saturation",
    explanation: "How hard the metadata service path is driven relative to its modeled capacity.",
    realWorldMapping: "Closest signal to MDS/MDT-side saturation pressure.",
    whyItMatters: "Persistently high values indicate namespace pressure and metadata queue risk.",
    modeledToday: true,
  },
  "throughput-fulfillment": {
    id: "throughput-fulfillment",
    category: "metric",
    label: "Throughput fulfillment",
    hoverTitle: "Delivered vs requested data",
    explanation: "Delivered throughput divided by requested throughput over the run.",
    realWorldMapping: "Directional health signal for shared striped data path plus fabric delivery.",
    whyItMatters: "Low fulfillment points toward storage-path or network ceilings.",
    modeledToday: true,
  },
  "queue-burden": {
    id: "queue-burden",
    category: "metric",
    label: "Queue burden",
    hoverTitle: "Admission pressure share",
    explanation: "Portion of ticks where jobs waited for compute admission.",
    realWorldMapping: "Represents scheduler/resource-allocation pressure in multi-tenant clusters.",
    whyItMatters: "High queue burden suggests compute supply or concurrency mismatch.",
    modeledToday: true,
  },
  "checkpoint-active-tick-share": {
    id: "checkpoint-active-tick-share",
    category: "metric",
    label: "Checkpoint-active tick share",
    hoverTitle: "Checkpoint activity share",
    explanation: "Portion of ticks where checkpoint logic was active.",
    realWorldMapping: "Captures periodic save pressure common in AI/HPC training workflows.",
    whyItMatters: "Higher values can correlate with bursty writes and pause-heavy behavior.",
    modeledToday: true,
  },
  "bottleneck-transitions": {
    id: "bottleneck-transitions",
    category: "metric",
    label: "Bottleneck transitions",
    hoverTitle: "Limiter switching count",
    explanation: "Number of times the dominant pressure label changed across ticks.",
    realWorldMapping: "Indicates stability vs shifting contention across compute/storage/network domains.",
    whyItMatters: "High transition counts suggest mixed constraints and harder tuning isolation.",
    modeledToday: true,
  },
  "longest-dominant-streak": {
    id: "longest-dominant-streak",
    category: "metric",
    label: "Longest dominant streak",
    hoverTitle: "Longest stable limiter span",
    explanation: "Longest uninterrupted run of one dominant bottleneck class.",
    realWorldMapping: "Shows how sustained a specific pressure domain remained.",
    whyItMatters: "Long streaks provide clearer target for one-variable tuning experiments.",
    modeledToday: true,
  },
  "bottleneck-confidence": {
    id: "bottleneck-confidence",
    category: "metric",
    label: "Bottleneck confidence",
    hoverTitle: "Attribution confidence",
    explanation: "Confidence label/score for run-level dominant bottleneck attribution.",
    realWorldMapping: "A deterministic evidence confidence indicator, not an external benchmark certainty.",
    whyItMatters: "Lower confidence implies closer competing pressures or mixed behavior.",
    modeledToday: true,
  },
  "dominant-time-share": {
    id: "dominant-time-share",
    category: "metric",
    label: "Dominant time share",
    hoverTitle: "Dominant label coverage",
    explanation: "Fraction of ticks governed by the dominant run-level bottleneck kind.",
    realWorldMapping: "Describes dominance persistence of one subsystem pressure in the scenario.",
    whyItMatters: "Higher shares imply clearer primary limiter for targeted changes.",
    modeledToday: true,
  },
  "shared-scratch": {
    id: "shared-scratch",
    category: "architecture",
    label: "Shared scratch",
    hoverTitle: "Shared parallel workspace",
    explanation: "Cluster-visible shared workspace for active jobs on a parallel filesystem.",
    realWorldMapping: "Maps to Lustre-like shared parallel scratch deployment, including managed offerings.",
    whyItMatters: "This is the main storage side the current simulator models.",
    modeledToday: true,
  },
  "local-scratch": {
    id: "local-scratch",
    category: "architecture",
    label: "Local scratch",
    hoverTitle: "Per-node temporary storage",
    explanation: "Fast node-local temporary space that is not shared between compute nodes.",
    realWorldMapping: "Common in HPC clusters for staging and temporary files local to each node.",
    whyItMatters: "Important operationally, but not modeled as a separate I/O path in this simulator today.",
    modeledToday: false,
  },
  "long-lived-storage": {
    id: "long-lived-storage",
    category: "architecture",
    label: "Home/lab/project storage",
    hoverTitle: "Longer-lived storage tier",
    explanation: "Durable collaborative data spaces outside short-lived shared scratch behavior.",
    realWorldMapping: "Maps to institutional home, lab, or project storage tiers.",
    whyItMatters: "Provides lifecycle context, but this tier is conceptual in the current run model.",
    modeledToday: false,
  },
  "metadata-path": {
    id: "metadata-path",
    category: "architecture",
    label: "Metadata path",
    hoverTitle: "Namespace control path",
    explanation: "Path for opens, creates, stats, and namespace operations.",
    realWorldMapping: "Directional analogue of metadata services in Lustre-like environments.",
    whyItMatters: "Metadata pressure can dominate small-file and high-churn workloads.",
    modeledToday: true,
  },
  "data-path": {
    id: "data-path",
    category: "architecture",
    label: "Data path",
    hoverTitle: "Shared payload path",
    explanation: "Path carrying read/write payload bytes for shared storage traffic.",
    realWorldMapping: "Represents the shared filesystem data transport path.",
    whyItMatters: "Data-path limits directly affect delivered throughput and wait-on-data behavior.",
    modeledToday: true,
  },
  "striped-data-path": {
    id: "striped-data-path",
    category: "architecture",
    label: "Striped data path",
    hoverTitle: "Parallel striped payload flow",
    explanation: "Shared data path spread across multiple storage targets using striping.",
    realWorldMapping: "Maps to Lustre-style striping across OST inventory.",
    whyItMatters: "Striping behavior links control choices like OST inventory and stripe width to throughput.",
    modeledToday: true,
  },
  "shared-filesystem": {
    id: "shared-filesystem",
    category: "architecture",
    label: "Shared filesystem",
    hoverTitle: "Parallel shared namespace",
    explanation: "Shared cluster filesystem serving many compute clients at once.",
    realWorldMapping: "Directional concept alignment with Lustre-style shared parallel filesystems.",
    whyItMatters: "This is the main architectural scope of the simulator.",
    modeledToday: true,
  },
  "compute-clients": {
    id: "compute-clients",
    category: "architecture",
    label: "Compute clients",
    hoverTitle: "Storage client nodes",
    explanation: "Compute nodes acting as clients of network and shared storage services.",
    realWorldMapping: "Maps to Lustre client behavior from CPU/GPU nodes.",
    whyItMatters: "Clarifies that compute demand and storage services are distinct roles.",
    modeledToday: true,
  },
  "ddn-exascaler-managed-lustre": {
    id: "ddn-exascaler-managed-lustre",
    category: "architecture",
    label: "DDN EXAScaler / managed Lustre style",
    hoverTitle: "Production packaging concept",
    explanation: "Example production packaging of a Lustre-like shared parallel filesystem architecture.",
    realWorldMapping: "Directional architecture mapping only; not an exact vendor benchmark model.",
    whyItMatters: "Helps learners relate simulator concepts to real deployment families without overclaiming equivalence.",
    modeledToday: false,
  },
};

const CONCEPT_IDS = Object.keys(CONCEPTS) as HpcLabConceptId[];

export const getHpcLabConcept = (id: HpcLabConceptId): HpcLabConcept => CONCEPTS[id];

export const listHpcLabConcepts = (): HpcLabConcept[] => CONCEPT_IDS.map((id) => CONCEPTS[id]);
