import { Button } from "@/components/ui/button";
import { getOutreachPreview, resolveSequenceContext } from "@/lib/job-hunter/conversationUi";
import type { ConversationTarget, JobPosting, OutreachSequence } from "@/lib/job-hunter/types";

import { formatDate, formatDateTime } from "./conversationFormat";
import { SequenceCard } from "./SequenceCard";

export function DraftedOutreachSection({ drafted, jobsById, targetsById, draftEdits, setDraftEdit, onEditSave, onCopy, onMarkSent, onSkip }: { drafted: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget>; draftEdits: Record<string, string>; setDraftEdit: (id: string, value: string) => void; onEditSave: (id: string) => void; onCopy: (value: string) => void; onMarkSent: (id: string) => void; onSkip: (id: string) => void }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Drafted Outreach</h2>{drafted.length === 0 ? <p className="text-sm text-foreground/70">No drafts or queued outreach yet.</p> : drafted.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); const value = draftEdits[sequence.id] ?? getOutreachPreview(sequence); return <SequenceCard key={sequence.id} sequence={sequence} subtitle={<><strong>{ctx.company}</strong>{ctx.title ? ` · ${ctx.title}` : ""}{ctx.target?.name ? ` · ${ctx.target.name}` : ""}{ctx.target?.relationshipType ? ` · ${ctx.target.relationshipType}` : ""}</>} value={value} onEdit={(next) => setDraftEdit(sequence.id, next)} onSave={() => onEditSave(sequence.id)} onCopy={() => onCopy(value)} actions={[{ label: "Mark Sent", onClick: () => onMarkSent(sequence.id) }, { label: "Skip", variant: "outline", onClick: () => onSkip(sequence.id) }]} />; })}</section>;
}

export function FollowUpsDueSection({ followUpsDue, jobsById, targetsById, draftEdits, setDraftEdit, onEditSave, onCopy, onMarkSent, onSkip, onSnooze }: { followUpsDue: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget>; draftEdits: Record<string, string>; setDraftEdit: (id: string, value: string) => void; onEditSave: (id: string) => void; onCopy: (value: string) => void; onMarkSent: (id: string) => void; onSkip: (id: string) => void; onSnooze: (id: string) => void }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Follow-ups Due</h2>{followUpsDue.length === 0 ? <p className="text-sm text-foreground/70">No follow-ups due today.</p> : followUpsDue.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); const value = draftEdits[sequence.id] ?? getOutreachPreview(sequence); return <article key={sequence.id} className="space-y-2 rounded-lg border border-border/60 p-4 text-sm"><p><strong>{ctx.company}</strong>{ctx.target?.name ? ` · ${ctx.target.name}` : ""}</p><p className="text-xs text-foreground/70">Due {formatDate(sequence.dueAt)} · {sequence.stage}</p><textarea className="min-h-24 w-full rounded border p-2" value={value} onChange={(event) => setDraftEdit(sequence.id, event.target.value)} /><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => onEditSave(sequence.id)}>Edit</Button><Button type="button" variant="secondary" onClick={() => onCopy(value)}>Copy</Button><Button type="button" onClick={() => onMarkSent(sequence.id)}>Mark Sent</Button><Button type="button" variant="outline" onClick={() => onSkip(sequence.id)}>Skip</Button><Button type="button" variant="outline" onClick={() => onSnooze(sequence.id)}>Snooze 2 business days</Button></div></article>; })}</section>;
}

export function ActiveConversationsSection({ activeReplies, jobsById, targetsById, onMarkOutcome }: { activeReplies: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget>; onMarkOutcome: (sequenceId: string, type: "reply_received" | "conversation_started" | "recruiter_screen" | "interview_scheduled" | "rejected" | "closed_no_response") => void }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Active Conversations</h2>{activeReplies.length === 0 ? <p className="text-sm text-foreground/70">No active replies yet.</p> : activeReplies.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); return <article key={sequence.id} className="rounded-lg border border-border/60 p-4 text-sm"><p><strong>{ctx.target?.name ?? "Unknown contact"}</strong> · {ctx.company}</p><p className="text-xs text-foreground/70">{sequence.channel} · replied {formatDateTime(sequence.repliedAt)}</p><p className="mt-2 whitespace-pre-wrap">{getOutreachPreview(sequence)}</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => onMarkOutcome(sequence.id, "reply_received")}>Mark Reply Received</Button><Button type="button" variant="secondary" onClick={() => onMarkOutcome(sequence.id, "conversation_started")}>Mark Conversation Started</Button><Button type="button" variant="secondary" onClick={() => onMarkOutcome(sequence.id, "recruiter_screen")}>Mark Recruiter Screen</Button><Button type="button" variant="secondary" onClick={() => onMarkOutcome(sequence.id, "interview_scheduled")}>Mark Interview Scheduled</Button><Button type="button" variant="outline" onClick={() => onMarkOutcome(sequence.id, "rejected")}>Mark Rejected</Button><Button type="button" variant="outline" onClick={() => onMarkOutcome(sequence.id, "closed_no_response")}>Mark Closed No Response</Button></div></article>; })}</section>;
}

export function PipelineOutcomesPanel({ outcomeCounts }: { outcomeCounts: Record<string, number> }) {
  const rows: Array<[string, string]> = [
    ["reply_received", "Replies received"],
    ["conversation_started", "Conversations started"],
    ["referral_received", "Referrals"],
    ["recruiter_screen", "Recruiter screens"],
    ["interview_scheduled", "Interviews scheduled"],
    ["rejected", "Rejections"],
    ["offer_received", "Offers"],
    ["closed_no_response", "Closed no response"],
  ];
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Pipeline Outcomes</h2><div className="grid gap-3 md:grid-cols-4">{rows.map(([key, label]) => <article key={key} className="rounded border border-border/40 p-3"><p className="text-xs text-foreground/70">{label}</p><p className="text-2xl font-semibold">{outcomeCounts[key] ?? 0}</p></article>)}</div></section>;
}
