import { Button } from "@/components/ui/button";
import { getOutreachPreview, resolveSequenceContext } from "@/lib/job-hunter/conversationUi";
import type { ConversationTarget, JobPosting, OutreachSequence } from "@/lib/job-hunter/types";

import { formatDate, formatDateTime } from "./conversationFormat";
import { SequenceCard } from "./SequenceCard";

export function DraftedOutreachSection({ drafted, jobsById, targetsById, draftEdits, setDraftEdit, onEditSave, onCopy, onMarkSent, onSkip }: { drafted: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget>; draftEdits: Record<string, string>; setDraftEdit: (id: string, value: string) => void; onEditSave: (id: string) => void; onCopy: (value: string) => void; onMarkSent: (id: string) => void; onSkip: (id: string) => void }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Drafted Outreach</h2>{drafted.length === 0 ? <p className="text-sm text-foreground/70">No drafts or queued outreach yet.</p> : drafted.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); const value = draftEdits[sequence.id] ?? getOutreachPreview(sequence); return <SequenceCard key={sequence.id} sequence={sequence} subtitle={<><strong>{ctx.company}</strong>{ctx.title ? ` · ${ctx.title}` : ""}{ctx.target?.name ? ` · ${ctx.target.name}` : ""}{ctx.target?.relationshipType ? ` · ${ctx.target.relationshipType}` : ""}</>} value={value} onEdit={(next) => setDraftEdit(sequence.id, next)} onSave={() => onEditSave(sequence.id)} onCopy={() => onCopy(value)} actions={[{ label: "Mark Sent", onClick: () => onMarkSent(sequence.id) }, { label: "Skip", variant: "outline", onClick: () => onSkip(sequence.id) }]} />; })}</section>;
}

export function FollowUpsDueSection({ followUpsDue, jobsById, targetsById, draftEdits, setDraftEdit, onEditSave, onCopy, onMarkSent, onSkip, onSnooze }: { followUpsDue: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget>; draftEdits: Record<string, string>; setDraftEdit: (id: string, value: string) => void; onEditSave: (id: string) => void; onCopy: (value: string) => void; onMarkSent: (id: string) => void; onSkip: (id: string) => void; onSnooze: (id: string) => void }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Follow-ups Due</h2>{followUpsDue.length === 0 ? <p className="text-sm text-foreground/70">No follow-ups due today.</p> : followUpsDue.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); const value = draftEdits[sequence.id] ?? getOutreachPreview(sequence); return <article key={sequence.id} className="space-y-2 rounded-lg border border-border/60 p-4 text-sm"><p><strong>{ctx.company}</strong>{ctx.target?.name ? ` · ${ctx.target.name}` : ""}</p><p className="text-xs text-foreground/70">Due {formatDate(sequence.dueAt)} · {sequence.stage}</p><textarea className="min-h-24 w-full rounded border p-2" value={value} onChange={(event) => setDraftEdit(sequence.id, event.target.value)} /><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => onEditSave(sequence.id)}>Edit</Button><Button type="button" variant="secondary" onClick={() => onCopy(value)}>Copy</Button><Button type="button" onClick={() => onMarkSent(sequence.id)}>Mark Sent</Button><Button type="button" variant="outline" onClick={() => onSkip(sequence.id)}>Skip</Button><Button type="button" variant="outline" onClick={() => onSnooze(sequence.id)}>Snooze 2 business days</Button></div></article>; })}</section>;
}

export function ActiveConversationsSection({ activeReplies, jobsById, targetsById }: { activeReplies: OutreachSequence[]; jobsById: Record<string, JobPosting>; targetsById: Record<string, ConversationTarget> }) {
  return <section className="space-y-3"><h2 className="text-xl font-semibold">Active Conversations</h2>{activeReplies.length === 0 ? <p className="text-sm text-foreground/70">No active replies yet.</p> : activeReplies.map((sequence) => { const ctx = resolveSequenceContext(sequence, jobsById, targetsById); return <article key={sequence.id} className="rounded-lg border border-border/60 p-4 text-sm"><p><strong>{ctx.target?.name ?? "Unknown contact"}</strong> · {ctx.company}</p><p className="text-xs text-foreground/70">{sequence.channel} · replied {formatDateTime(sequence.repliedAt)}</p><p className="mt-2 whitespace-pre-wrap">{getOutreachPreview(sequence)}</p></article>; })}</section>;
}
